
String apiToken= "aHMRQr0ZUK8YVV7UmgwtKe8SzIz9QhCDi6hAxCHM1l04ihtc4OYGlc4P4qMp";
bool isDarkTheme = false;
String dbURL = "vit.1devfull.info";


List <Map<String, Object>> listDataTzas = [
  {
    "id": " ldfsnbglslgnskgfdsg",
    "name": " Иванов Л.А.",
    "gps": "35468441154 : 65168445",
    "time": "12-45",
    "status": false
  },
  {
    "id": " sdtgjsryjysrjy",
    "name": " Петров С.А.",
    "gps": "35468441154 : 65168445",
    "time": "14-45",
    "status": false
  },
  { "id": " asderththj", "name": " Сидоров В.Ф.", "gps": "465456564 : 65168445",
    "time": "15-56", "status": false},
  {
    "id": " srtjrytj",
    "name": " Афанасьев Д.А.",
    "gps": "354684441154 : 65168445",
    "time": "13-45",
    "status": false
  },
];

List <Map<String, Object>> listDataDevices = [
  {
    "id": " ldfsnbglslgnskgfdsg",
    "name": " Иванов Л.А.",
    "gps": "35468441154 : 65168445",
    "time": "12-45",
    "status": false
  },
  {
    "id": " sdtgjsryjysrjy",
    "name": " Петров С.А.",
    "gps": "35468441154 : 65168445",
    "time": "14-45",
    "status": false
  },
  { "id": " asderththj", "name": " Сидоров В.Ф.", "gps": "465456564 : 65168445",
    "time": "15-56", "status": false},
  {
    "id": " srtjrytj",
    "name": " Афанасьев Д.А.",
    "gps": "354684441154 : 65168445",
    "time": "13-45",
    "status": false
  },
];

List <Map<String, Object>> listDataCustomers = [
  {
    "id": "sdakfhglsdhbgfn",
    "name": "Алексеев И.П.",
    "gps": "21641551323: 35164543",
    "time": "15-48",
    "status": true,
    "phone": "+79999403678"
  },
  {
    "id": "sdakfhglsdhbgfn",
    "name": "Павлов К.П.",
    "gps": "21641551323: 35164543",
    "time": "15-48",
    "status": true,
    "phone": "+79999405645"
  },
  {
    "id": "sdakfhglsdhbgfn",
    "name": "Егоров И.Е.",
    "gps": "21641551323: 35164543",
    "time": "15-48",
    "status": true,
    "phone": "+79999407854"
  },
];

List <Map<String, Object>> listDataAviacompanies = [];
List <Map<String, Object>> listDataParkings = [];
List <Map<String, Object>> listDataPlanes = [];

List <Map<String, Object>> listDataEvents = [
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": "123456789",
    "idEvent": " 789456132",
    "nameEmployer": "Морозов Илья Владимирович",
    "timeCreate": "15-50",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "16-10",
    "timeEndFact": "16-50",
    "timeStartNeed": "16-00",
    "timeEndNeed": "16-40",
    "parkNumber": "1",
    "modelPlane": "ТУ-204-100",
    "numberPlane": "7023",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " 456123789",
    "idEvent": "987654321",
    "nameEmployer": "Юсупов Надир Наильевич",
    "timeCreate": "12-00",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": "12-30",
    "timeEndFact": "13-00",
    "timeStartNeed": "12-30",
    "timeEndNeed": "13-00",
    "parkNumber": "2",
    "modelPlane": "Боинг 737-800",
    "numberPlane": "7019",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 250,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
  {
    "idTZA": " ТЗА не назначен",
    "idEvent": " ТЗА не назначен",
    "nameEmployer": "Ответсвенный не назначен",
    "timeCreate": " Время не указанно",
    "statusEmployer": "В процессе выполенения данной задачи",
    "timeStartFact": " Время не указанно",
    "timeEndFact": " Время не указанно",
    "timeStartNeed": " Время не указанно",
    "timeEndNeed": " Время не указанно",
    "parkNumber": "1",
    "modelPlane": "Модель самолета",
    "numberPlane": "номер самолета",
    "statusFuelEnd": true,
    "statusStartFuel": false,
    "needTime": "30 минут",
    "qFuel": 100,
    "typeFuel": "Авиабензин"
  },
];

Map <String, String> pagesTitles = {
  "devises": "ТЗА",
  "admins": "Управление администраторами",
  "custumers": "Сотрудники",
  "events": "Задачи",
  "adminInfo": "Управление администраторами",
  "deviceInfo": "ТЗА",
  "customerInfo": "Сотрудники",
  "eventInfo": "Задачи",
};

List <Map<String, Object>> listDataAdmins = [
  { "name": "Игнатов И.П.", "status": true, "phone": "+79999403678"},
  { "name": "Морин А.П.", "status": true, "phone": "+79999403789"},
  { "name": "Алексеев Г.П.", "status": true, "phone": "+79999403123"},
];
Map<String, dynamic> taskDataExample = {
  "id": "2",
  "manager_id": "3",
  "operator_id": "4",
  "parking_id": "2",
  "airline_id": "1",
  "plane_id": "7",
  "number_plane": "345234556",
  "refueller_id": "1",
  "fuel_amount": "120",
  "fuel_type": "fuel",
  "time_to_start": "2020-05-20 20:33:43",
  "allowed_time": "40",
  "arrival_number": "STBMKS-100",
  "arrival_number_desc": "\u0421\u0442\u0430\u043c\u0431\u0443\u043b - \u041c\u043e\u0441\u043a\u0432\u0430",
  "departure_number": "MKSSTB-101",
  "departure_number_desc": "\u041c\u043e\u0441\u043a\u0432\u0430 - \u0421\u0442\u0430\u043c\u0431\u0443\u043b",
  "created_at": "2020-05-19 21:19:21",
  "updated_at": "2020-05-19 21:19:21",
  "statuses": [
    {
      "id": "2",
      "task_id": "2",
      "producer_id": "3",
      "status": {
        "code": "created",
        "text": "\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0430"
      },
      "comment": "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439",
      "created_at": "2020-05-19 21:19:21",
      "updated_at": "2020-05-19 21:19:21",
      "producer": {
        "id": "3",
        "name": "\u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432 \u0414\u043c\u0438\u0442\u0440\u0438\u0439",
        "phoneNumber": "79032001291",
        "role": "manager",
        "api_token": ""+apiToken+"",
        "password": "password",
        "created": "2020-05-17 00:37:17",
        "modified": "2020-05-17 10:43:25",
        "removed": "0"
      },
      "status_code": "created"
    }
  ],
  "current_status": {
    "id": "2",
    "task_id": "2",
    "producer_id": "3",
    "status": {
      "code": "created",
      "text": "\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0430"
    },
    "comment": "\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439",
    "created_at": "2020-05-19 21:19:21",
    "updated_at": "2020-05-19 21:19:21",
    "producer": {
      "id": "3",
      "name": "\u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432 \u0414\u043c\u0438\u0442\u0440\u0438\u0439",
      "phoneNumber": "79032001291",
      "role": "manager",
      "api_token": ""+apiToken+"",
      "password": "password",
      "created": "2020-05-17 00:37:17",
      "modified": "2020-05-17 10:43:25",
      "removed": "0"
    },
    "status_code": "created"
  },
  "manager": {
    "id": "3",
    "name": "\u0414\u043c\u0438\u0442\u0440\u0438\u0435\u0432 \u0414\u043c\u0438\u0442\u0440\u0438\u0439",
    "phoneNumber": "79032001291",
    "role": "manager",
    "api_token": ""+apiToken+"",
    "password": "password",
    "created": "2020-05-17 00:37:17",
    "modified": "2020-05-17 10:43:25",
    "removed": "0"
  },
  "operator": {
    "id": "4",
    "name": "Volodimir",
    "phoneNumber": "79008007362",
    "role": "operator",
    "api_token": "O2lJwYboFnKbdpwVTUTOKh24bpntliiiq43kyQwzpI8rSHyM5JaKBdZjRWGQ",
    "password": "password",
    "created": "2020-05-17 09:53:47",
    "modified": "2020-05-17 09:53:47",
    "removed": "0"
  },
  "airline": {
    "id": "1",
    "name": "\u0410\u044d\u0440\u043e\u0444\u043b\u043e\u0442",
    "comment": "\u041a\u0440\u0443\u0442\u0430\u044f \u0430\u0432\u0438\u0430\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f",
    "created_at": "2020-05-19 10:41:14",
    "updated_at": "2020-05-19 11:08:24",
    "removed": "0"
  },
  "plane": {
    "id": "7",
    "model": "\u0422\u0443-154",
    "maxfuel": "180",
    "comment": "zzz"
  },
  "parking": {"id": "2", "number": "4392-S", "mapId": "svg4394"},
  "refueller": {"id": "1", "number": "333333232333", "position": null},
  "is_expired_start": 0,
  "is_expired_done": 0,
  "is_filled_valid": 0,
  "options": {
    "airlines": [
      {
        "id": "2",
        "name": "S7",
        "comment": "\u041c\u044b \u0438 \u0432 \u043a\u043e\u0441\u043c\u043e\u0441 \u043b\u0435\u0442\u0430\u0435\u043c",
        "created_at": "2020-05-19 10:42:07",
        "updated_at": "2020-05-19 10:42:07",
        "removed": "0"
      },
      {
        "id": "3",
        "name": "\u0410\u0432\u0438\u0430\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f \u041f\u043e\u0431\u0435\u0434\u0430 \u0422\u0435\u0441\u0442",
        "comment": "\u0422\u041d\u0430\u043c",
        "created_at": "2020-05-19 17:33:34",
        "updated_at": "2020-05-19 17:34:12",
        "removed": "1"
      },
      {
        "id": "1",
        "name": "\u0410\u044d\u0440\u043e\u0444\u043b\u043e\u0442",
        "comment": "\u041a\u0440\u0443\u0442\u0430\u044f \u0430\u0432\u0438\u0430\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f",
        "created_at": "2020-05-19 10:41:14",
        "updated_at": "2020-05-19 11:08:24",
        "removed": "0"
      }
    ],
    "parkings": [
      {"id": "2", "number": "4392-S", "mapId": "svg4394"},
      {"id": "1", "number": "4392-T", "mapId": "svg4392"}
    ],
    "refuellers": [{"id": "1", "number": "333333232333", "position": null}]
  },
  "lang": {
    "statuses": {
      "created": "\u041f\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u0430",
      "process": "\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043d\u0430\u0447\u0430\u0442\u043e",
      "done": "\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043d\u0430\u0447\u0430\u0442\u043e",
      "cancelled": "\u041e\u0442\u043c\u0435\u043d\u0435\u043d\u0430"
    },
    "fuel_types": {
      "fuel": "\u0410\u0432\u0438\u0430\u0431\u0435\u043d\u0437\u0438\u043d",
      "kerosene": "\u0410\u0432\u0438\u0430\u043a\u0435\u0440\u043e\u0441\u0438\u043d"
    }
  }
};